/* Blind Wordle — Keyboard-only responsive version
   Rules:
   - 6 attempts (rows 0..5), each 5 letters
   - For first 5 guesses (rows 0..4) feedback colors are hidden
   - After the 5th guess (i.e., after submitting row 4), reveal colors for guesses 0..4
     and start a 60s timer for the final guess (row 5).
   - If timer expires before final guess submitted -> player loses and answer is shown.
*/
const WORDS = [
  "ABOUT",
  "ABOVE",
  "ACORN",
  "ACUTE",
  "ADAPT",
  "ADMIT",
  "AHEAD",
  "ALIVE",
  "ALLOW",
  "ALMOST",
  "ALONE",
  "ALONG",
  "ALPHA",
  "AMBER",
  "AMONG",
  "ANGEL",
  "ANGRY",
  "APPLE",
  "APART",
  "APPLY",
  "APRON",
  "AQUIN",
  "ARENA",
  "ARGUE",
  "ARISE",
  "ASIDE",
  "ASLEEP",
  "ASPECT",
  "ASSAY",
  "ASSERT",
  "ASSET",
  "ATLAS",
  "ATONE",
  "AUDIO",
  "AWARE",
  "AWFUL",
  "AWAKE",
  "AWARD",
  "AZURE",
  "BACON",
  "BADGE",
  "BADLY",
  "BAKER",
  "BALSA",
  "BANDA",
  "BANJO",
  "BARGE",
  "BASIC",
  "BASIS",
  "BATHE",
  "BEACH",
  "BEARD",
  "BEAST",
  "BEGET",
  "BEGIN",
  "BEGUN",
  "BEING",
  "BELOW",
  "BEMUD",
  "BENCH",
  "BENDY",
  "BENEF",
  "BENTO",
  "BERRY",
  "BESET",
  "BESTY",
  "BETTA",
  "BETTY",
  "BIBLE",
  "BICEP",
  "BIGGY",
  "BIGHT",
  "BIKER",
  "BILGE",
  "BINGO",
  "BIPOD",
  "BIRCH",
  "BIRTH",
  "BISHA",
  "BISKY",
  "BLACK",
  "BLAME",
  "BLANK",
  "BLAST",
  "BLAZE",
  "BLEAK",
  "BLEED",
  "BLESS",
  "BLIMP",
  "BLIND",
  "BLINK",
  "BLOCK",
  "BLOOD",
  "BLOOM",
  "BLOWN",
  "BLUER",
  "BLUFF",
  "BLUNT",
  "BLURB",
  "BLURT",
  "BOAST",
  "BOBBY",
  "BONGO",
  "BONUS",
  "BOOST",
  "BOOTH",
  "BOOTY",
  "BOOZE",
  "BORNE",
  "BOUGH",
  "BOUND",
  "BOWEL",
  "BOXED",
  "BOXER",
  "BRAID",
  "BRAIN",
  "BRAKE",
  "BRAND",
  "BRASS",
  "BRAVE",
  "BREAD",
  "BREAK",
  "BREAM",
  "BREED",
  "BRICK",
  "BRIDE",
  "BRIEF",
  "BRIGHT",
  "BRING",
  "BRISK",
  "BROAD",
  "BROKE",
  "BROOM",
  "BROWN",
  "BRUSH",
  "BRUTE",
  "BUILD",
  "BUILT",
  "BULLY",
  "BUNCH",
  "BURST",
  "BUSHY",
  "BUTTE",
  "BUYER",
  "BYLAW",
  "CABAL",
  "CABIN",
  "CABLE",
  "CACTI",
  "CAKE",
  "CALVE",
  "CAMEO",
  "CANAL",
  "CANDY",
  "CANOE",
  "CANON",
  "CAPER",
  "CARAT",
  "CARGO",
  "CAROL",
  "CARRY",
  "CARVE",
  "CASEY",
  "CASHY",
  "CATER",
  "CAUSE",
  "CAVEA",
  "CEASE",
  "CEDAR",
  "CHAIR",
  "CHALK",
  "CHAMP",
  "CHARM",
  "CHART",
  "CHASE",
  "CHASM",
  "CHEAP",
  "CHEAT",
  "CHECK",
  "CHEEK",
  "CHEER",
  "CHEST",
  "CHIEF",
  "CHILD",
  "CHILL",
  "CHIME",
  "CHINA",
  "CHIPM",
  "CHIVE",
  "CHOIR",
  "CHOKE",
  "CHORD",
  "CHUCK",
  "CHUNK",
  "CHURN",
  "CIDER",
  "CIGAR",
  "CINCH",
  "CINEO",
  "CIVIC",
  "CIVIL",
  "CLAIM",
  "CLANG",
  "CLANK",
  "CLASH",
  "CLASP",
  "CLASS",
  "CLEAN",
  "CLEAR",
  "CLEAT",
  "CLEFT",
  "CLERK",
  "CLICK",
  "CLIFF",
  "CLIMB",
  "CLING",
  "CLINK",
  "CLOCK",
  "CLOSE",
  "CLOTH",
  "CLOUD",
  "CLOVEN",
  "CLOWN",
  "CLOVE",
  "CLUMP",
  "CLUNG",
  "COACH",
  "COAST",
  "COBWE",
  "CODEX",
  "COLIC",
  "COLON",
  "COLOR",
  "COMET",
  "COMFY",
  "COMMA",
  "CONDO",
  "CONIC",
  "CONGO",
  "CORAL",
  "CORNY",
  "COUCH",
  "COULD",
  "COUNT",
  "COURT",
  "COVEN",
  "COVER",
  "COVET",
  "CRACK",
  "CRAFT",
  "CRAMP",
  "CRANE",
  "CRASH",
  "CRAVE",
  "CRAWL",
  "CRAZY",
  "CREAK",
  "CREAM",
  "CREDO",
  "CREEK",
  "CREEP",
  "CREME",
  "CREST",
  "CRIME",
  "CRISP",
  "CRISP",
  "CRONE",
  "CROOK",
  "CROSS",
  "CROWD",
  "CROWN",
  "CRUDE",
  "CRUEL",
  "CRUMB",
  "CRUMP",
  "CRUSH",
  "CRYPT",
  "CUBIC",
  "CUMIN",
  "CURIO",
  "CURLY",
  "CURRY",
  "CURSE",
  "CURVE",
  "CYCLE",
  "CYNIC",
  "DAIRY",
  "DAISY",
  "DALLY",
  "DANCE",
  "DANDY",
  "DARER",
  "DARING",
  "DASHY",
  "DEATH",
  "DEBAT",
  "DEBUT",
  "DECAL",
  "DECAY",
  "DECK",
  "DECOR",
  "DECOY",
  "DECRE",
  "DEDDY",
  "DEED",
  "DEEPY",
  "DEFY",
  "DEITY",
  "DELAY",
  "DELTA",
  "DEMON",
  "DENIM",
  "DENSE",
  "DEPUT",
  "DEPTH",
  "DEREK",
  "DERRY",
  "DETER",
  "DEUCE",
  "DEVIL",
  "DIARY",
  "DICEY",
  "DIETA",
  "DIGHT",
  "DIGIT",
  "DILEM",
  "DINER",
  "DINGY",
  "DIPPY",
  "DIRGE",
  "DIRTY",
  "DISCO",
  "DISHY",
  "DITCH",
  "DIVAN",
  "DIVER",
  "DOCKY",
  "DODGE",
  "DOGGY",
  "DOLPH",
  "DONUT",
  "DOOMY",
  "DOORW",
  "DOTTY",
  "DOUBT",
  "DOUGH",
  "DOZEN",
  "DRAIN",
  "DRAMA",
  "DRAWL",
  "DREAM",
  "DRESS",
  "DRIFT",
  "DRILL",
  "DRINK",
  "DRIVE",
  "DROLL",
  "DRONE",
  "DROOP",
  "DROWN",
  "DRUNK",
  "DRYLY",
  "DUCHY",
  "DULLY",
  "DUMMY",
  "DURUM",
  "DUSTY",
  "DWARF",
  "DWELL",
  "DYING",
  "EAGER",
  "EAGLE",
  "EARLY",
  "EARTH",
  "EASEL",
  "EATEN",
  "EATER",
  "EBONY",
  "ECHOY",
  "EDGE",
  "EEL",
  "EIGHT",
  "ELDER",
  "ELECT",
  "ELITE",
  "ELOPE",
  "ELUDE",
  "EMBLE",
  "EMILY",
  "EMPTY",
  "ENACT",
  "ENDE",
  "ENJOY",
  "ENOUGH",
  "ENROL",
  "ENTRY",
  "ENVY",
  "EPIC",
  "EPOCH",
  "EPOXY",
  "EQUAL",
  "EQUIP",
  "ERASE",
  "ERROR",
  "ESSAY",
  "ETHAN",
  "ETHIC",
  "EVERY",
  "EVICT",
  "EVIL",
  "EXACT",
  "EXCEL",
  "EXIST",
  "EXIT",
  "EXPAT",
  "EXPEL",
  "EXTOL",
  "EXTRA",
  "FABLE",
  "FACE",
  "FACET",
  "FAIRY",
  "FAITH",
  "FALSE",
  "FANCY",
  "FANCY",
  "FANCY",
  "FANCY",
  "FANCY",
  "FANCY",
  "FANCY",
  "FANCY",
  "FARCE",
  "FATAL",
  "FATTY",
  "FAUNA",
  "FAULT",
  "FAVOR",
  "FEAR",
  "FEAST",
  "FEEL",
  "FEET",
  "FELON",
  "FEMUR",
  "FENCE",
  "FERRY",
  "FESTY",
  "FETCH",
  "FEWER",
  "FIBER",
  "FIERY",
  "FIFTY",
  "FIGHT",
  "FILET",
  "FINAL",
  "FINCH",
  "FINER",
  "FIRST",
  "FISHY",
  "FISTY",
  "FIXED",
  "FIXED",
  "FIXER",
  "FLAIR",
  "FLAKE",
  "FLAME",
  "FLANK",
  "FLARE",
  "FLASH",
  "FLAT",
  "FLAUNT",
  "FLAWN",
  "FLECK",
  "FLEET",
  "FLESH",
  "FLICK",
  "FLIER",
  "FLING",
  "FLINT",
  "FLIRT",
  "FLOAT",
  "FLOCK",
  "FLOOD",
  "FLOOR",
  "FLORA",
  "FLOUR",
  "FLOWN",
  "FLUFF",
  "FLUID",
  "FLUKE",
  "FLUSH",
  "FLUTE",
  "FLYBY",
  "FOAMY",
  "FOCUS",
  "FOGGY",
  "FOLIO",
  "FOLKS",
  "FORCE",
  "FORGE",
  "FORGO",
  "FORUM",
  "FOSSA",
  "FOUDY",
  "FOUND",
  "FOYER",
  "FRAIL",
  "FRAME",
  "FRANK",
  "FRAUD",
  "FREAK",
  "FREER",
  "FRENCH",
  "FRESH",
  "FRIAR",
  "FRIED",
  "FROCK",
  "FROND",
  "FRONT",
  "FROST",
  "FROTH",
  "FROWN",
  "FROZE",
  "FRUIT",
  "FUDGY",
  "FUELS",
  "FULL",
  "FULLY",
  "FUNGI",
  "FUNKY",
  "FUNNY",
  "FUROR",
  "FUZZY",
  "GAFFE",
  "GAILY",
  "GAIN",
  "GAMUT",
  "GANJA",
  "GATOR",
  "GAUNT",
  "GAUZE",
  "GAVEL",
  "GAYER",
  "GEEK",
  "GEESE",
  "GENIE",
  "GENUS",
  "GHOST",
  "GIANT",
  "GIDDY",
  "GIVEN",
  "GIVER",
  "GLAD",
  "GLADE",
  "GLAM",
  "GLAND",
  "GLARE",
  "GLASS",
  "GLEAM",
  "GLEAN",
  "GLIDE",
  "GLIMP",
  "GLINT",
  "GLITZ",
  "GLOOM",
  "GLORY",
  "GLOZE",
  "GLUEY",
  "GLYPH",
  "GNASH",
  "GNOME",
  "GOATY",
  "GOLD",
  "GOLFY",
  "GONER",
  "GORGE",
  "GORGY",
  "GOUGE",
  "GRACE",
  "GRADE",
  "GRAIN",
  "GRAND",
  "GRANT",
  "GRAPE",
  "GRAPH",
  "GRASP",
  "GRASS",
  "GRAVE",
  "GRAVY",
  "GRAZE",
  "GREAT",
  "GREED",
  "GREEN",
  "GREET",
  "GRIEF",
  "GRIME",
  "GRIND",
  "GRIP",
  "GROAN",
  "GROIN",
  "GROOM",
  "GROUP",
  "GROUT",
  "GROVE",
  "GROWL",
  "GROWN",
  "GRUDG",
  "GUANO",
  "GUARD",
  "GUESS",
  "GUEST",
  "GUIDE",
  "GUILE",
  "GUISE",
  "GULLY",
  "GUMBO",
  "GUPPY",
  "GUSTO",
  "GUTSY",
  "GYPSY",
  "HABIT",
  "HACKY",
  "HAIRY",
  "HALVE",
  "HANDY",
  "HAPPY",
  "HARDY",
  "HARPY",
  "HARSH",
  "HASTE",
  "HASTY",
  "HATCH",
  "HAUNT",
  "HAVEN",
  "HAWKY",
  "HEADY",
  "HEARD",
  "HEART",
  "HEATH",
  "HEAVE",
  "HEAVY",
  "HELIX",
  "HELLO",
  "HENRY",
  "HERBY",
  "HERD",
  "HERO",
  "HEXAD",
  "HICCA",
  "HICKY",
  "HIDDEN",
  "HIKE",
  "HINDO",
  "HINGE",
  "HIPPO",
  "HISSY",
  "HITCH",
  "HOBBY",
  "HOIST",
  "HOLLY",
  "HOMER",
  "HONEY",
  "HONKY",
  "HONOR",
  "HORNY",
  "HORSE",
  "HOTEL",
  "HOUSE",
  "HOVER",
  "HOWDY",
  "HUMAN",
  "HUMID",
  "HUMOR",
  "HUNKY",
  "HURRY",
  "HUTCH",
  "HYMN",
  "HYPNO",
  "ICY",
  "IDEAL",
  "IDIO",
  "IDIOT",
  "IGLOO",
  "IMAGE",
  "IMPLY",
  "INBOX",
  "INCUR",
  "INDEX",
  "INDIE",
  "INERT",
  "INFER",
  "INFLA",
  "INFO",
  "INGOT",
  "INLAY",
  "INLET",
  "INNER",
  "INPUT",
  "INSET",
  "INTEL",
  "INTER",
  "INTO",
  "INURE",
  "IRATE",
  "IRON",
  "ISLET",
  "ISSUE",
  "ITALY",
  "ITCHY",
  "IVORY",
  "JABBY",
  "JACKY",
  "JACOB",
  "JADED",
  "JAUNT",
  "JELLY",
  "JERKY",
  "JEWEL",
  "JIGGY",
  "JINX",
  "JOCKY",
  "JOINT",
  "JOKEY",
  "JOUST",
  "JOY",
  "JUDGE",
  "JUICE",
  "JUICY",
  "JUMBO",
  "JUMPY",
  "JUNKY",
  "JUROR",
  "KABOB",
  "KAYAK",
  "KEBAB",
  "KELLY",
  "KICKY",
  "KIDDO",
  "KIND",
  "KIND",
  "KINKY",
  "KISER",
  "KITE",
  "KITTY",
  "KNEAD",
  "KNEEL",
  "KNEEL",
  "KNIFE",
  "KNIT",
  "KNOCK",
  "KNOT",
  "KUDOS",
  "LABEL",
  "LABOR",
  "LACEY",
  "LADEN",
  "LADLE",
  "LAGER",
  "LAKEY",
  "LAMER",
  "LANCE",
  "LAND",
  "LAPSE",
  "LARGE",
  "LARGO",
  "LASER",
  "LATER",
  "LATEX",
  "LATHE",
  "LAUGH",
  "LAVAL",
  "LAVEN",
  "LAXLY",
  "LAYER",
  "LEAFY",
  "LEAKY",
  "LEAP",
  "LEARN",
  "LEASE",
  "LEAVE",
  "LEDGE",
  "LEERY",
  "LEFT",
  "LEGAL",
  "LEGIT",
  "LEMON",
  "LEND",
  "LENTO",
  "LEMON",
  "LEPER",
  "LETRA",
  "LEVEL",
  "LEVER",
  "LIBEL",
  "LICE",
  "LIEGE",
  "LIGHT",
  "LIKE",
  "LIMBO",
  "LIME",
  "LIMIT",
  "LINEA",
  "LINEN",
  "LINER",
  "LINGO",
  "LINKY",
  "LION",
  "LIPID",
  "LITRE",
  "LIVER",
  "LIVED",
  "LLAMA",
  "LOAD",
  "LOBBY",
  "LOCAL",
  "LOCHS",
  "LOCUS",
  "LOGAN",
  "LOGIC",
  "LOHAN",
  "LOLLY",
  "LONELY",
  "LOOPY",
  "LOOSE",
  "LORD",
  "LOTUS",
  "LOVER",
  "LOWER",
  "LOYAL",
  "LUCKY",
  "LUNCH",
  "LUNGE",
  "LUSTY",
  "LYNCH",
  "LYRIC",
  "MACAB",
  "MACRO",
  "MADLY",
  "MAGMA",
  "MAID",
  "MAJOR",
  "MALE",
  "MANIA",
  "MANGO",
  "MAPLE",
  "MARCH",
  "MARGE",
  "MARSH",
  "MASON",
  "MASSY",
  "MATCH",
  "MATEO",
  "MATTE",
  "MAUVE",
  "MAVEN",
  "MAYBE",
  "MAYBE",
  "MAYOR",
  "MEALY",
  "MEANT",
  "MEATY",
  "MEDIA",
  "MELEE",
  "MELON",
  "MERCY",
  "MERIT",
  "MERRY",
  "MESHY",
  "METAL",
  "METRO",
  "MIDST",
  "MIGHT",
  "MINCE",
  "MINER",
  "MINOR",
  "MINTY",
  "MINUS",
  "MIRTH",
  "MODAL",
  "MODEL",
  "MODEM",
  "MODEST",
  "MOIST",
  "MOLAR",
  "MONEY",
  "MONEY",
  "MONTH",
  "MOOD",
  "MOODY",
  "MORAL",
  "MOSEY",
  "MOSSY",
  "MOTEL",
  "MOTIF",
  "MOTOR",
  "MOTTO",
  "MOULT",
  "MOUND",
  "MOUNT",
  "MOURN",
  "MOUSE",
  "MOUST",
  "MOUTH",
  "MOVER",
  "MOVIE",
  "MUCH",
  "MUDDY",
  "MUGGY",
  "MULCH",
  "MUMMY",
  "MUNCH",
  "MUSIC",
  "MUSHY",
  "MYOPY",
  "MYTH",
  "NAIVE",
  "NAMED",
  "NARROW",
  "NASTY",
  "NATAL",
  "NAVEL",
  "NEAR",
  "NEATO",
  "NEEDY",
  "NERDY",
  "NERVY",
  "NEVER",
  "NEWLY",
  "NEXUS",
  "NICHE",
  "NIGHT",
  "NINTH",
  "NITRO",
  "NOBLE",
  "NOISY",
  "NOMAD",
  "NOONE",
  "NORMA",
  "NORTH",
  "NOSEY",
  "NOTCH",
  "NOTED",
  "NOTIFY",
  "NUDGE",
  "NURSE",
  "OASIS",
  "OATHY",
  "OCEAN",
  "OCTOR",
  "OFTEN",
  "OLDIE",
  "OLIVE",
  "ONION",
  "ONSET",
  "OPERA",
  "OPINE",
  "OPTIC",
  "ORBIT",
  "ORDEAL",
  "ORDER",
  "ORGAN",
  "OTHER",
  "OTTER",
  "OUGHT",
  "OVAL",
  "OVEN",
  "OVERT",
  "OWNER",
  "OXYGEN",
  "PACEY",
  "PALMS",
  "PANEL",
  "PANIC",
  "PAPPY",
  "PARER",
  "PARKA",
  "PARRY",
  "PARTY",
  "PASTE",
  "PASTY",
  "PATCH",
  "PATIO",
  "PATSY",
  "PAUSE",
  "PAYER",
  "PEACE",
  "PEACH",
  "PEARL",
  "PECKY",
  "PEDAL",
  "PENCE",
  "PENNY",
  "PEONY",
  "PERIL",
  "PERKY",
  "PETAL",
  "PETTY",
  "PHASE",
  "PHONE",
  "PHOTO",
  "PHYL",
  "PIANO",
  "PICKY",
  "PILOT",
  "PINEY",
  "PINKY",
  "PINTO",
  "PIQUE",
  "PITHY",
  "PIXEL",
  "PLACE",
  "PLANK",
  "PLANT",
  "PLATE",
  "PLAY",
  "PLED",
  "PLOD",
  "PLUCK",
  "PLUMP",
  "PLUSH",
  "POACH",
  "PODIA",
  "POET",
  "POINT",
  "POKER",
  "POLAR",
  "POLE",
  "POLKA",
  "POOCH",
  "POPPY",
  "PORCH",
  "PORGY",
  "PORTE",
  "POSED",
  "POSER",
  "POTTY",
  "POUCH",
  "POUND",
  "POWER",
  "PRAWN",
  "PRAY",
  "PREEN",
  "PRESS",
  "PRICE",
  "PRICK",
  "PRIME",
  "PRINT",
  "PRIOR",
  "PRISM",
  "PRIVE",
  "PRIZE",
  "PROBE",
  "PROMO",
  "PROUD",
  "PROVE",
  "PROWL",
  "PRUNE",
  "PSALM",
  "PSHAW",
  "PUDGY",
  "PUFFY",
  "PULSE",
  "PUNCH",
  "PUPPY",
  "PURE",
  "PURGE",
  "PUSHY",
  "PUPPET",
  "PUZZY",
  "PYGMY",
  "QUACK",
  "QUAFF",
  "QUAIL",
  "QUAKE",
  "QUASH",
  "QUASI",
  "QUEEN",
  "QUEER",
  "QUELL",
  "QUERY",
  "QUEST",
  "QUEUE",
  "QUICK",
  "QUID",
  "QUIET",
  "QUILL",
  "QUILT",
  "QUITE",
  "QUIVER",
  "QUOIN",
  "QUOTE",
  "RABBI",
  "RABID",
  "RACKY",
  "RADAR",
  "RADIO",
  "RAFFY",
  "RAGAS",
  "RALLY",
  "RAMEN",
  "RANCH",
  "RANDY",
  "RANGE",
  "RAPID",
  "RATIO",
  "RAZOR",
  "REACH",
  "REACT",
  "READY",
  "REALM",
  "REBEL",
  "RECIP",
  "RECUR",
  "REFER",
  "REIGN",
  "RELAX",
  "RELAY",
  "RELIC",
  "RELIT",
  "RELY",
  "REMED",
  "RENEW",
  "RENTO",
  "REPAY",
  "REPEL",
  "REPLY",
  "REPLY",
  "RESIN",
  "REVEAL",
  "REVUE",
  "RHYME",
  "RIGHT",
  "RINSE",
  "RISKY",
  "RIVER",
  "ROBOT",
  "ROBUST",
  "RODEO",
  "ROGER",
  "ROGUE",
  "ROUND",
  "ROVER",
  "ROWDY",
  "ROYAL",
  "RUDDY",
  "RUGBY",
  "RUIN",
  "RUMBA",
  "RUMOR",
  "RUSTY",
  "SABER",
  "SABLE",
  "SADLY",
  "SAINT",
  "SALAD",
  "SALLY",
  "SALTY",
  "SALVE",
  "SAMBA",
  "SANER",
  "SASSY",
  "SATIN",
  "SAUCY",
  "SAUTE",
  "SAVOR",
  "SCAFF",
  "SCALE",
  "SCALP",
  "SCALY",
  "SCAMP",
  "SCANT",
  "SCARE",
  "SCARF",
  "SCARP",
  "SCARY",
  "SCENE",
  "SCENT",
  "SCOPE",
  "SCORE",
  "SCOUR",
  "SCOUT",
  "SCRAP",
  "SCREAM",
  "SCREW",
  "SCRUB",
  "SCUBA",
  "SEAWE",
  "SEDAN",
  "SEDGE",
  "SEEDY",
  "SEEM",
  "SEIZE",
  "SELDOM",
  "SENSE",
  "SERUM",
  "SERVE",
  "SEVEN",
  "SHADE",
  "SHADY",
  "SHAKE",
  "SHAKY",
  "SHALE",
  "SHALL",
  "SHAME",
  "SHAPE",
  "SHARE",
  "SHARP",
  "SHAWN",
  "SHEAR",
  "SHEEN",
  "SHEEP",
  "SHEER",
  "SHELF",
  "SHELL",
  "SHIFT",
  "SHINY",
  "SHIRE",
  "SHIRT",
  "SHOCK",
  "SHOOT",
  "SHORE",
  "SHORT",
  "SHOTS",
  "SHOUL",
  "SHOUT",
  "SHOVE",
  "SHOWN",
  "SHRUG",
  "SHUN",
  "SHUT",
  "SICKY",
  "SIDEL",
  "SIESTA",
  "SIGHT",
  "SIGMA",
  "SILKY",
  "SILO",
  "SINCE",
  "SINEW",
  "SINGE",
  "SINUS",
  "SITUP",
  "SIXTY",
  "SKATE",
  "SKIER",
  "SKILL",
  "SKIMP",
  "SKIRT",
  "SKULK",
  "SLACK",
  "SLATE",
  "SLEEP",
  "SLEET",
  "SLEW",
  "SLICE",
  "SLICK",
  "SLIME",
  "SLIMY",
  "SLING",
  "SLINK",
  "SLOPE",
  "SLOSH",
  "SLOTH",
  "SLOWN",
  "SLUICE",
  "SLUMP",
  "SLURP",
  "SLUSH",
  "SMALL",
  "SMART",
  "SMEAR",
  "SMELL",
  "SMILE",
  "SMITE",
  "SMOKE",
  "SMOKY",
  "SMOOTH",
  "SMOTE",
  "SNAKE",
  "SNAKY",
  "SNARE",
  "SNARL",
  "SNEAK",
  "SNIDE",
  "SNIFF",
  "SNIPE",
  "SNOUT",
  "SNOWY",
  "SOAKY",
  "SOBER",
  "SOLAR",
  "SOLVE",
  "SONAR",
  "SONIC",
  "SOPPY",
  "SORRY",
  "SOUGH",
  "SOUND",
  "SOUTH",
  "SPADE",
  "SPANK",
  "SPARE",
  "SPARK",
  "SPASM",
  "SPAWN",
  "SPEAK",
  "SPEAR",
  "SPECK",
  "SPEED",
  "SPELL",
  "SPEND",
  "SPICE",
  "SPICY",
  "SPIKE",
  "SPIKY",
  "SPIN",
  "SPITE",
  "SPLAT",
  "SPLIT",
  "SPOIL",
  "SPOKE",
  "SPOOF",
  "SPOON",
  "SPORT",
  "SPOUT",
  "SPRAY",
  "SPREE",
  "SPRIG",
  "SPRIT",
  "SPURT",
  "SQUAD",
  "SQUARE",
  "SQUAT",
  "SQUID",
  "STAB",
  "STACK",
  "STAFF",
  "STAGE",
  "STALE",
  "STAMP",
  "STAND",
  "STARE",
  "STARK",
  "START",
  "STATE",
  "STAY",
  "STEAD",
  "STEAK",
  "STEAL",
  "STEAM",
  "STEEL",
  "STEEP",
  "STEER",
  "STEM",
  "STEVE",
  "STICK",
  "STIFF",
  "STILL",
  "STING",
  "STINK",
  "STOCK",
  "STOMP",
  "STONE",
  "STONER",
  "STOOP",
  "STOP",
  "STORE",
  "STORK",
  "STORM",
  "STORY",
  "STOUT",
  "STOVE",
  "STRAW",
  "STRAY",
  "STREP",
  "STREW",
  "STRIP",
  "STROP",
  "STUCK",
  "STUDY",
  "STUFF",
  "STUMP",
  "STUNG",
  "STUNK",
  "STUNT",
  "STYLE",
  "SUGAR",
  "SUITE",
  "SULKY",
  "SUMMA",
  "SUNNY",
  "SUNUP",
  "SUPER",
  "SURGE",
  "SWAMP",
  "SWANK",
  "SWARM",
  "SWEAT",
  "SWEEP",
  "SWEET",
  "SWELL",
  "SWIFT",
  "SWING",
  "SWIRL",
  "SWOON",
  "SWOOP",
  "SWORD",
  "SWORE",
  "SWORN",
  "SYNTH",
  "SYRUP",
  "TABBY",
  "TABLE",
  "TABOO",
  "TACIT",
  "TACKY",
  "TALON",
  "TAMER",
  "TANGA",
  "TANGO",
  "TANGY",
  "TANGO",
  "TARDY",
  "TAROT",
  "TASTY",
  "TATTO",
  "TAUNT",
  "TAWNY",
  "TEACH",
  "TEASE",
  "TEETH",
  "TENSE",
  "TERMS",
  "TERSE",
  "TESLA",
  "THANK",
  "THEFT",
  "THEIR",
  "THEME",
  "THERE",
  "THERM",
  "THICK",
  "THIEF",
  "THING",
  "THINK",
  "THIRD",
  "THORN",
  "THOSE",
  "THREE",
  "THREW",
  "THROB",
  "THROW",
  "THUMB",
  "TIBIA",
  "TIDAL",
  "TIGER",
  "TIGHT",
  "TILDE",
  "TILED",
  "TILTY",
  "TIMER",
  "TIMID",
  "TINGE",
  "TINNY",
  "TINTY",
  "TIRED",
  "TODAY",
  "TOKEN",
  "TONAL",
  "TONER",
  "TONIC",
  "TOPAZ",
  "TOPIC",
  "TORSO",
  "TOTAL",
  "TOTEM",
  "TOUCH",
  "TOUGH",
  "TOWEL",
  "TOWER",
  "TOWNS",
  "TOXIC",
  "TRACE",
  "TRACK",
  "TRACT",
  "TRADE",
  "TRAIL",
  "TRAIN",
  "TRAIT",
  "TRASH",
  "TREAD",
  "TREAT",
  "TREES",
  "TREND",
  "TRIAD",
  "TRIAL",
  "TRIBE",
  "TRICK",
  "TRIPE",
  "TRITE",
  "TROLL",
  "TRUMP",
  "TRUNK",
  "TRUSS",
  "TRUST",
  "TRUTH",
  "TRYST",
  "TUBAL",
  "TUDOR",
  "TUFFY",
  "TULIP",
  "TUMMY",
  "TUNE",
  "TURBO",
  "TUTOR",
  "TWEED",
  "TWICE",
  "TWIGS",
  "TWILL",
  "TWINE",
  "TWINK",
  "TWIRL",
  "TWOO",
  "TYING",
  "TYLER",
  "ULCER",
  "ULTRA",
  "UMBRA",
  "UNBEL",
  "UNCLE",
  "UNDER",
  "UNDUE",
  "UNIFY",
  "UNION",
  "UNITE",
  "UNITY",
  "UNIX",
  "UNTIL",
  "UNWED",
  "UPSET",
  "URBAN",
  "URINE",
  "USAGE",
  "USEFUL",
  "USUAL",
  "UTTER",
  "VACAY",
  "VAGUE",
  "VALET",
  "VALID",
  "VALUE",
  "VAPID",
  "VARY",
  "VAULT",
  "VEGET",
  "VENAL",
  "VENOM",
  "VENUE",
  "VERGE",
  "VERVE",
  "VETER",
  "VICE",
  "VIDEO",
  "VIGOR",
  "VILLA",
  "VINYL",
  "VIRAL",
  "VIRUS",
  "VISIT",
  "VITAL",
  "VIVID",
  "VODKA",
  "VOILA",
  "VOICE",
  "VOMIT",
  "VOTER",
  "VOWEL",
  "WACKO",
  "WACKY",
  "WADER",
  "WADGE",
  "WAGON",
  "WAIST",
  "WALEY",
  "WALK",
  "WALKY",
  "WALLY",
  "WARBY",
  "WARD",
  "WARM",
  "WARTY",
  "WASH",
  "WASTE",
  "WATCH",
  "WATER",
  "WAVE",
  "WEAK",
  "WEALTH",
  "WEARY",
  "WEAVE",
  "WEEDY",
  "WEEK",
  "WEIGH",
  "WEIRD",
  "WELL",
  "WETTY",
  "WHALE",
  "WHAT",
  "WHEAT",
  "WHEEL",
  "WHERE",
  "WHICH",
  "WHIFF",
  "WHILE",
  "WHILE",
  "WHIM",
  "WHIP",
  "WHOLE",
  "WHY",
  "WICK",
  "WIDOW",
  "WIDEY",
  "WIGGY",
  "WILD",
  "WILEY",
  "WILL",
  "WILLY",
  "WINDY",
  "WINK",
  "WIPER",
  "WISE",
  "WISH",
  "WITCH",
  "WITTY",
  "WIZEN",
  "WOBBLY",
  "WOEBE",
  "WOMAN",
  "WONKY",
  "WOOD",
  "WOOLY",
  "WORD",
  "WORK",
  "WORLD",
  "WORRY",
  "WORSE",
  "WORST",
  "WORTH",
  "WOULD",
  "WOUND",
  "WRECK",
  "WREST",
  "WRING",
  "WRIST",
  "WRITE",
  "WRONG",
  "YACHT",
  "YARD",
  "YEAR",
  "YEAST",
  "YELPY",
  "YETI",
  "YIELD",
  "YUMMY",
  "ZANY",
  "ZEBRA",
  "ZEDO",
  "ZESTY",
  "ZINC",
  "ZINGY",
  "ZIPPY",
  "ZONAL",
  "ZONED"
];
// pick random target uppercase
let target = WORDS[Math.floor(Math.random()*WORDS.length)].toUpperCase();
const WORDSET = new Set(WORDS);

const ROWS = 6, COLS = 5;
let currentRow = 0, currentCol = 0;
let grid = Array.from({length: ROWS}, ()=> Array(COLS).fill(''));
let solved = false;
let timerInterval = null;
let timeLeft = 60; // seconds for final guess

// DOM
const boardEl = document.getElementById('board');
const statusEl = document.getElementById('status');
const timerEl = document.getElementById('timer');
const timeLeftEl = document.getElementById('time-left');
const restartBtn = document.getElementById('restart');
const revealBtn = document.getElementById('reveal');

// build board rows & tiles
for(let r=0;r<ROWS;r++){
  const row = document.createElement('div'); row.className='row';
  for(let c=0;c<COLS;c++){
    const tile = document.createElement('div');
    tile.className='tile';
    tile.id = `tile-${r}-${c}`;
    tile.setAttribute('data-row', r);
    tile.setAttribute('data-col', c);
    row.appendChild(tile);
  }
  boardEl.appendChild(row);
}

// (no on-screen keyboard) — listen to physical keyboard
window.addEventListener('keydown', (e) => {
  if(solved) return;
  if(e.ctrlKey || e.metaKey || e.altKey) return; // ignore combos
  if(e.key === 'Enter') {
    e.preventDefault();
    handleEnter();
    return;
  }
  if(e.key === 'Backspace') {
    e.preventDefault();
    handleBackspace();
    return;
  }
  const k = e.key.toUpperCase();
  if(k.length === 1 && k >= 'A' && k <= 'Z') {
    handleLetter(k);
  }
});

// control buttons
restartBtn.addEventListener('click', resetGame);
revealBtn.addEventListener('click', ()=>{ if(!solved) endGame(false, `Answer: ${target}`); });

function handleLetter(letter){
  if(currentCol >= COLS) return;
  grid[currentRow][currentCol] = letter;
  const tile = document.getElementById(`tile-${currentRow}-${currentCol}`);
  tile.textContent = letter;
  tile.classList.add('filled');
  currentCol++;
}

function handleBackspace(){
  if(currentCol <= 0) return;
  currentCol--;
  grid[currentRow][currentCol] = '';
  const tile = document.getElementById(`tile-${currentRow}-${currentCol}`);
  tile.textContent = '';
  // only remove filled if row empty at that col
  if(!tile.textContent) tile.classList.remove('filled');
}

function handleEnter(){
  if(currentCol !== COLS) {
    showStatus('Not enough letters');
    return;
  }
  const attempt = grid[currentRow].join('');
  if(!WORDSET.has(attempt)) {
    showStatus('Not in word list');
    return;
  }

  // evaluation (internal) for later reveal
  const evals = evaluate(attempt, target);

  // If currentRow < 5 (rows 0..4), we DON'T show colors yet - keep tiles plain (but filled)
  // After submitting row 4 (the 5th guess), we reveal all first five rows and start timer
  if(currentRow < 4) {
    // simply accept guess and advance
    currentRow++; currentCol = 0;
    showStatus('');
  } else if(currentRow === 4) {
    // submitted 5th guess -> reveal rows 0..4 colors now, start final-timer and move to final row
    revealRowsUpTo(4); // reveal first five guesses (rows 0..4)
    startFinalTimer();
    currentRow++; currentCol = 0; // move to final row (5)
    showStatus('Final guess started — 60s!');
  } else {
    // currentRow === 5 (final guess submitted)
    // stop timer and reveal final row & check win/lose
    revealRow(5);
    if(evals.every(x=>x==='correct')) {
      endGame(true, '🎉 Nice! You guessed the word.');
    } else {
      endGame(false, `❌ Time/Guesses done. Word was ${target}`);
    }
    return;
  }

  // If the submitted guess itself is correct and before final reveal, we should also handle instant win.
  if(evals.every(x=>x==='correct')) {
    // if this happens before the 5-guess reveal rule (rare), treat as win immediately
    revealRow(currentRow - 1); // reveal the winning row visually
    endGame(true, '🎉 You guessed it!');
    return;
  }

  // clear any status after submit
  setTimeout(()=> showStatus(''), 900);
}

// evaluate: returns array of 'correct'|'present'|'absent' for each letter
function evaluate(guess, solution) {
  const g = guess.split('');
  const s = solution.split('');
  const result = Array(COLS).fill('absent');
  const counts = {};

  // first pass correct
  for(let i=0;i<COLS;i++){
    if(g[i] === s[i]) { result[i] = 'correct'; s[i] = null; }
    else { counts[s[i]] = (counts[s[i]] || 0) + 1; }
  }
  // second pass present
  for(let i=0;i<COLS;i++){
    if(result[i] === 'correct') continue;
    if(counts[g[i]]) { result[i] = 'present'; counts[g[i]]--; }
  }
  return result;
}

// reveal a single row (apply classes)
function revealRow(r) {
  const attempt = grid[r].join('');
  const ev = evaluate(attempt, target);
  for(let c=0;c<COLS;c++){
    const tile = document.getElementById(`tile-${r}-${c}`);
    // animation: add a flip-like delay
    setTimeout(()=> {
      tile.classList.remove('filled');
      tile.classList.add(ev[c]);
    }, c*160);
  }
}

// reveal rows from 0..r inclusive
function revealRowsUpTo(r) {
  for(let row=0; row<=r; row++){
    // small timeout chain so reveal looks sequential
    (row => setTimeout(()=> revealRow(row), row*250))(row);
  }
}

// status messages
let statusTimer = null;
function showStatus(msg, timeout=1600){
  clearTimeout(statusTimer);
  statusEl.textContent = msg;
  if(timeout>0) statusTimer = setTimeout(()=> statusEl.textContent = '', timeout);
}

// Timer for final guess (row 5)
function startFinalTimer(){
  // if already running, don't start again
  if(timerInterval) return;
  timeLeft = 60;
  timerEl.classList.remove('hidden');
  timeLeftEl.textContent = timeLeft;
  timerInterval = setInterval(()=> {
    timeLeft--;
    timeLeftEl.textContent = timeLeft;
    if(timeLeft <= 0) {
      clearInterval(timerInterval);
      timerInterval = null;
      // time up -> reveal answer and end game
      endGame(false, `⏳ Time's up! The word was ${target}`);
    }
  }, 1000);
}

// end game handler
function endGame(win, message){
  solved = true;
  // reveal everything (if some rows not yet revealed, show them)
  // reveal all rows that have letters
  for(let r=0;r<ROWS;r++){
    const rowStr = grid[r].join('');
    if(rowStr.trim().length === 0) continue;
    // reveal but only if not already revealed
    revealRow(r);
  }

  if(timerInterval) { clearInterval(timerInterval); timerInterval = null; }
  timerEl.classList.add('hidden');
  showStatus(message, 4000);
}

// restart
function resetGame(){
  // clear timer & state
  if(timerInterval){ clearInterval(timerInterval); timerInterval=null; }
  solved = false;
  currentRow = 0; currentCol = 0;
  grid = Array.from({length: ROWS}, ()=> Array(COLS).fill(''));
  statusEl.textContent = '';
  timerEl.classList.add('hidden');

  // pick new target
  target = WORDS[Math.floor(Math.random()*WORDS.length)].toUpperCase();

  // clear tiles UI
  for(let r=0;r<ROWS;r++){
    for(let c=0;c<COLS;c++){
      const tile = document.getElementById(`tile-${r}-${c}`);
      tile.textContent = '';
      tile.className = 'tile';
    }
  }
}

// small helper to reveal answer quickly for testing (button)
function quickReveal(){
  endGame(false, `Answer: ${target}`);
}

// Expose some helpers on window for debugging (optional)
window._blindwordle = {
  reset: resetGame,
  reveal: quickReveal,
  target: () => target
};
